# workflowの名前
name: Build & Test

# トリガーの設定
on:
  push:
    branches: [master] # mainブランチの場合はmainに変更
  pull_request:
    branches: [master]

env:
  POETRY_VERSION: 1.1.10
  POETRY_URL: https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py

jobs:
  build:
    name: Build & Test
    # 実行環境として `ubuntu-latest` という名前のものを選ぶ
    runs-on: ubuntu-latest
    # 複数の Python のバージョンでテストするために `strategy.matrix` を設定する
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      # リポジトリをチェックアウトする
      # See: https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Python のランタイムをセットアップする
      # バージョンは `strategy.matrix` に並べたものを指定する
      # See: https://github.com/actions/setup-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Poetry そのものをインストールする
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 仮想環境に入って異なるpythonバージョンで実行する
      - name: Enter the virtual environment
        run: poetry env use ${{ matrix.python-version }}

      # インストールした Poetry を使って必要な Python パッケージをインストールする
      - name: Install Dependencies
        run: poetry install --no-interaction

      # 構文チェック
      - name: Lint with flake8
        run: |
          make lint

      # pytest を実行する
      - name: Test with pytest
        run: |
          make test

      # build
      - name: Build BlackJack.exe
        run: |
          make build
